added deploy.yml fix message status

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,17 +14,6 @@ jobs:
     if: contains(github.event.comment.body, '/deploy')
     runs-on: ubuntu-latest
     steps:
-      - name: Check label for production deployment
-        if: contains(github.event.comment.body, '/deploy prod')
-        run: |
-          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels)
-          echo "Checking if 'deploy' label is applied..."
-          if [[ $LABELS != *"deploy"* ]]; then
-            echo "Label 'deploy' not found. Exiting."
-            exit 1
-          fi
-          echo "Label 'deploy' found. Proceeding to production deployment."
-
       - name: Checkout repository
         uses: actions/checkout@v4
 
@@ -34,11 +23,49 @@ jobs:
         run: |
           if [[ "${{ github.event.comment.body }}" == *"/deploy pre"* ]]; then
             echo "environment=pre" >> $GITHUB_ENV
+            echo "pre" >> $GITHUB_ENV
           elif [[ "${{ github.event.comment.body }}" == *"/deploy prod"* ]]; then
             echo "environment=production" >> $GITHUB_ENV
+            echo "prod" >> $GITHUB_ENV
           else
             echo "Invalid environment. Exiting."
             exit 1
+          fi
+
+      # Check label for production deployment
+      - name: Check label for production deployment
+        id: check-label
+        if: env.environment == 'prod'
+        run: |
+          LABELS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels)
+          echo "Checking if 'deploy' label is applied..."
+          if [[ $LABELS != *"deploy"* ]]; then
+            echo "Label 'deploy' not found. Exiting."
+            echo "false" >> $GITHUB_ENV
+            exit 1
+          fi
+          echo "Label 'deploy' found. Proceeding to production deployment."
+          echo "true" >> $GITHUB_ENV
+
+      # Send status message
+      - name: Send status message
+        run: |
+          if [[ "${{ env.environment }}" == "production" && "${{ env.false }}" == "false" ]]; then
+            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
+              -d '{"body": "Deployment to production will proceed as the required label is present."}'
+          elif [[ "${{ env.environment }}" == "production" ]]; then
+            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
+              -d '{"body": "Deployment to production was not executed because the required label is missing."}'
+            exit 1
+          elif [[ "${{ env.environment }}" == "pre" ]]; then
+            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
+              -d '{"body": "Deployment to pre-environment will proceed."}'
           fi
 
       # Install dependencies
@@ -58,7 +85,7 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: './dist'
+          path: "./dist"
 
       # Deploy based on environment
       - name: Deploy
